import './globals.css';
import { MedievalSharp } from 'next/font/google';

const medieval = MedievalSharp({
  weight: ['400'],
  style: 'normal',
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-medieval',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={medieval.variable}>{children}</body>
    </html>
  );
}
